export enum ErrorCodes {
  // Generic
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_INPUT = "INVALID_INPUT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  // Auth
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_TOKEN = "INVALID_TOKEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  // User
  USER_NOT_FOUND = "USER_NOT_FOUND",
  DUPLICATE_USER = "DUPLICATE_USER",
  EMAIL_IN_USE = "EMAIL_IN_USE",
  USERNAME_IN_USE = "USERNAME_IN_USE",
  // Verification
  VERIFICATION_NOT_FOUND = "VERIFICATION_NOT_FOUND",
  VERIFICATION_EXPIRED = "VERIFICATION_EXPIRED",
  VERIFICATION_USED = "VERIFICATION_USED",
  // Configuration
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
  // Rate limiting
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  // Security
  INVALID_CSRF = "INVALID_CSRF",
  // Session
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_REVOKED = "SESSION_REVOKED",
  FAILED_TO_ROLL_SESSION = "FAILED_TO_ROLL_SESSION",
  // Password
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK",
  // Email
  EMAIL_INVALID = "EMAIL_INVALID",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  // Account
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_BANNED = "ACCOUNT_BANNED",
  ACCOUNT_DELETION = "ACCOUNT_DELETION",
}
