export enum ErrorCodes {
  // System Level
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  INVALID_INPUT = "INVALID_INPUT",
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",

  // Authentication
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN",
  AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS",

  // Session
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_REVOKED = "SESSION_REVOKED",
  SESSION_INVALID = "SESSION_INVALID",
  SESSION_LIMIT_EXCEEDED = "SESSION_LIMIT_EXCEEDED",

  // Verification
  VERIFICATION_NOT_FOUND = "VERIFICATION_NOT_FOUND",
  VERIFICATION_EXPIRED = "VERIFICATION_EXPIRED",
  VERIFICATION_USED = "VERIFICATION_USED",
  VERIFICATION_INVALID = "VERIFICATION_INVALID",

  // Account
  ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
  ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_REQUIRES_VERIFICATION = "ACCOUNT_REQUIRES_VERIFICATION",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",

  // Registration
  REGISTRATION_EMAIL_EXISTS = "REGISTRATION_EMAIL_EXISTS",
  REGISTRATION_USERNAME_EXISTS = "REGISTRATION_USERNAME_EXISTS",
  REGISTRATION_USER_EXISTS = "REGISTRATION_USER_EXISTS",
  REGISTRATION_DISABLED = "REGISTRATION_DISABLED",

  // Email
  EMAIL_INVALID = "EMAIL_INVALID",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  EMAIL_VERIFICATION_EXPIRED = "EMAIL_VERIFICATION_EXPIRED",
  EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED",
  EMAIL_SENDING_FAILED = "EMAIL_SENDING_FAILED",

  // Password
  PASSWORD_INVALID = "PASSWORD_INVALID",
  PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK",
  PASSWORD_RECENTLY_USED = "PASSWORD_RECENTLY_USED",
  PASSWORD_RESET_REQUIRED = "PASSWORD_RESET_REQUIRED",
  PASSWORD_RESET_EXPIRED = "PASSWORD_RESET_EXPIRED",

  // Security
  SECURITY_CSRF_INVALID = "SECURITY_CSRF_INVALID",
  SECURITY_RATE_LIMITED = "SECURITY_RATE_LIMITED",
  SECURITY_INVALID_IP = "SECURITY_INVALID_IP",
  SECURITY_SUSPICIOUS_ACTIVITY = "SECURITY_SUSPICIOUS_ACTIVITY",
  SECURITY_GEO_RESTRICTED = "SECURITY_GEO_RESTRICTED",

  // Rate Limiting
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  RATE_LIMIT_DISABLED = "RATE_LIMIT_DISABLED",
  RATE_LIMIT_ENDPOINT_DISABLED = "RATE_LIMIT_ENDPOINT_DISABLED",
}
